/**
 * Card Priority × Memory Analytics — replays every card's FSRS history and
 * aggregates per-card stats into 10 priority-percentile buckets plus an
 * overall KB row. Used by the new tab in WeightedShieldPopupView.
 *
 * Card population follows the `card.getAll()` + filter-by-remId pattern so
 * disabled / paused cards are included (matching other batch flows).
 * Priority is inherited from the owning Rem (read from the existing
 * allCardPriorityInfoKey cache); cards from rems missing in that cache are
 * skipped.
 */

import { RNPlugin, QueueInteractionScore } from '@remnote/plugin-sdk';
import { CardPriorityInfo } from './card_priority/types';
import {
  computeFSRSState,
  computeFSRSStatesPerReview,
  forgettingCurve,
  resolveWeights,
} from './fsrs';

export interface CardBucketStats {
  label: string;          // "0-10%" or "All KB"
  priorityRange: string;  // e.g. "6-12", or "—"
  // Population
  /** Every card record in the bucket, practicable or not. */
  cards: number;
  /**
   * Cards with no `nextRepetitionTime` — disabled in some way, or no longer
   * generated by their Rem. RemNote will never surface them, so they cannot be
   * due, cannot be practised, and must not sit in the denominator of anything
   * that describes practice. See lib/card_analytics_export.ts for the causes.
   */
  unscheduled: number;
  /**
   * Cards inside a paused deck. Pausing does NOT clear `nextRepetitionTime`, so
   * these keep a real due date and would otherwise be counted as due — RemNote
   * simply refuses to serve them. Counted separately from `unscheduled`; a card
   * that is both is counted here only (see lib/paused_decks.ts).
   * Always 0 when no paused-deck scan has run this session.
   */
  paused: number;
  /** cards − unscheduled − paused: the practicable population, and the
   *  denominator for donePct / newPct / stalePct below. */
  active: number;
  due: number;
  donePct: number;        // 0-100, (active - due) / active
  /** New cards among the ACTIVE ones — what you could still learn. */
  newCount: number;
  newPct: number;         // newCount / active
  /** New cards that are unscheduled — reported separately, never mixed in. */
  newUnscheduled: number;
  staleCount: number;
  stalePct: number;       // staleCount / active
  // Throughput — all aggregates use gradeable reps (Again/Hard/Good/Easy)
  // over the full history, with each rep's responseTime capped at cardCapMs
  // (matches study_dashboard / practiced_queues).
  totReps: number;        // total gradeable reps
  totTimeMs: number;      // total capped response time
  avgReps: number;        // totReps / cards
  avgTimeMs: number;      // totTimeMs / cards
  cpm: number;            // totReps / (totTimeMs / 60_000)
  avgTimePerRepMs: number;// totTimeMs / totReps
  avgCostMinPerYear: number; // mean of per-card cost over cards with cost
  // Outcome
  avgLapses: number;      // mean over non-new cards
  retention: number;      // 0-100, (gradeableReps - agains) / gradeableReps
  avgPredR: number;       // 0-100, mean predicted R over every step where r != null
  rDevPP: number;         // retention - avgPredR (percentage points)
  avgGrade: number;       // 1-4
  // FSRS current state (today)
  avgD: number;
  avgRtoday: number;      // 0-100
  avgS: number;           // days
}

export interface CardAnalyticsBreakdown {
  buckets: CardBucketStats[];   // length 10
  overall: CardBucketStats;
  totalCards: number;
  computedAt: number;
  /** Cards seen from card.getAll() whose rem was missing from the priority cache (skipped). */
  cardsSkippedNoPriority: number;
  /**
   * Whether pre-RESET history was excluded. Persisted in the cache so the view
   * can sync the toggle to the data it's showing and recompute on mismatch.
   */
  ignorePreReset: boolean;
  /**
   * The period applied to per-rep stats. Persisted so the view can sync its
   * picker to the data it's showing and recompute on mismatch. Stored as the
   * raw Period id + the resolved [startMs, endMs) bounds; the resolver is not
   * idempotent across midnights, so storing the bounds is safer than only the id.
   */
  period: string;          // raw Period id, e.g. 'thisYear'
  periodStartMs: number;
  periodEndMs: number;
  periodCustomStart: string;
  periodCustomEnd: string;
  /**
   * Pre-finalized stats per absolute-priority threshold T (index 0..100).
   * `byPriorityPrefix[T]` aggregates every card whose owning Rem's priority
   * is ≤ T — i.e. the subset "Priority ≤ T". The view's threshold slider
   * reads this directly, so dragging the slider is just an array lookup.
   * `byPriorityPrefix[100]` equals `overall` (modulo label / priorityRange).
   */
  byPriorityPrefix: CardBucketStats[];
  /** False when no paused-deck scan was available, so `paused` counts read 0
   *  because nothing was looked at — not because nothing is paused. */
  pausedScanApplied: boolean;
}

interface AccData {
  count: number;
  minPriority: number;
  maxPriority: number;
  due: number;
  unscheduled: number;
  paused: number;
  newCount: number;
  newUnscheduled: number;
  staleCount: number;
  // Throughput aggregates (all over gradeable reps in the FULL history, capped responseTime)
  totGradeableReps: number;
  totTimeMs: number;
  totAgains: number;
  // Outcome aggregates
  totLapses: number;
  nonNewCards: number;
  sumCost: number;
  cardsWithCost: number;
  sumPredR: number;
  predRCount: number;
  sumGrade: number;
  gradeCount: number;
  // FSRS aggregates
  sumD: number;
  sumS: number;
  sumRtoday: number;
  fsrsCount: number;
}

interface PerCardStats {
  isDue: boolean;
  isNew: boolean;
  isStale: boolean;
  /** No `nextRepetitionTime` — RemNote will never surface this card. */
  isUnscheduled: boolean;
  /** Inside a paused deck — schedulable, but the queue will not serve it. */
  isPaused: boolean;
  /** Gradeable repetitions over the FULL history (matches study_dashboard.cardReps). */
  gradeableReps: number;
  /** Sum of response time across gradeable reps, each capped at cardCapMs. */
  totalTimeMs: number;
  agains: number;
  lapses: number;
  cost: number | null;
  sumPredR: number;
  predRCount: number;
  sumGrade: number;
  gradeCount: number;
  d: number | null;
  s: number | null;
  rToday: number | null;
}

/**
 * Element-wise sum of two AccData. Used to build the by-priority prefix-sum
 * table — adding each priority bucket to the running total. minPriority /
 * maxPriority are merged by min/max; everything else is additive.
 */
function mergeAcc(a: AccData, b: AccData): AccData {
  return {
    count: a.count + b.count,
    minPriority: Math.min(a.minPriority, b.minPriority),
    maxPriority: Math.max(a.maxPriority, b.maxPriority),
    due: a.due + b.due,
    unscheduled: a.unscheduled + b.unscheduled,
    paused: a.paused + b.paused,
    newCount: a.newCount + b.newCount,
    newUnscheduled: a.newUnscheduled + b.newUnscheduled,
    staleCount: a.staleCount + b.staleCount,
    totGradeableReps: a.totGradeableReps + b.totGradeableReps,
    totTimeMs: a.totTimeMs + b.totTimeMs,
    totAgains: a.totAgains + b.totAgains,
    totLapses: a.totLapses + b.totLapses,
    nonNewCards: a.nonNewCards + b.nonNewCards,
    sumCost: a.sumCost + b.sumCost,
    cardsWithCost: a.cardsWithCost + b.cardsWithCost,
    sumPredR: a.sumPredR + b.sumPredR,
    predRCount: a.predRCount + b.predRCount,
    sumGrade: a.sumGrade + b.sumGrade,
    gradeCount: a.gradeCount + b.gradeCount,
    sumD: a.sumD + b.sumD,
    sumS: a.sumS + b.sumS,
    sumRtoday: a.sumRtoday + b.sumRtoday,
    fsrsCount: a.fsrsCount + b.fsrsCount,
  };
}

function makeAcc(): AccData {
  return {
    count: 0,
    minPriority: Infinity,
    maxPriority: -Infinity,
    due: 0,
    unscheduled: 0,
    paused: 0,
    newCount: 0,
    newUnscheduled: 0,
    staleCount: 0,
    totGradeableReps: 0,
    totTimeMs: 0,
    totAgains: 0,
    totLapses: 0,
    nonNewCards: 0,
    sumCost: 0,
    cardsWithCost: 0,
    sumPredR: 0,
    predRCount: 0,
    sumGrade: 0,
    gradeCount: 0,
    sumD: 0,
    sumS: 0,
    sumRtoday: 0,
    fsrsCount: 0,
  };
}

function isGradeable(score: QueueInteractionScore): boolean {
  return (
    score === QueueInteractionScore.AGAIN ||
    score === QueueInteractionScore.HARD ||
    score === QueueInteractionScore.GOOD ||
    score === QueueInteractionScore.EASY
  );
}

function gradeValue(score: QueueInteractionScore): number | null {
  switch (score) {
    case QueueInteractionScore.AGAIN: return 1;
    case QueueInteractionScore.HARD: return 2;
    case QueueInteractionScore.GOOD: return 3;
    case QueueInteractionScore.EASY: return 4;
    default: return null;
  }
}

function computeCardStats(
  card: any,
  weights: number[] | null,
  now: number,
  cardCapMs: number,
  ignorePreReset: boolean,
  startMs: number,
  endMs: number,
  isPaused: boolean,
): PerCardStats {
  const history = card.repetitionHistory ?? [];
  const sorted = [...history].sort((a: any, b: any) => a.date - b.date);

  // Effective history = post-RESET slice when the toggle is on, else the full
  // history. FSRS replay below also uses the effective history so D/R/S and
  // Avg pR stay consistent with the reps actually being counted.
  let effective: any[] = sorted;
  if (ignorePreReset) {
    const lastResetIdx = sorted.map((h: any) => h.score).lastIndexOf(QueueInteractionScore.RESET);
    if (lastResetIdx !== -1) effective = sorted.slice(lastResetIdx + 1);
  }

  const inPeriod = (h: any) => h && typeof h.date === 'number' && h.date >= startMs && h.date < endMs;
  const isAllPeriod = startMs <= 0;

  // ---- Period-filtered tallies (Reps, Time, Lapses, Retention, Grade) ----
  let gradeableReps = 0;
  let totalTimeMs = 0;
  let agains = 0;
  let sumGrade = 0;
  let gradeCount = 0;

  for (const h of effective) {
    if (!isGradeable(h.score)) continue;
    if (!inPeriod(h)) continue;
    gradeableReps++;
    const t = Math.min(Math.max(0, h.responseTime || 0), cardCapMs);
    totalTimeMs += t;
    if (h.score === QueueInteractionScore.AGAIN) agains++;
    const g = gradeValue(h.score);
    if (g !== null) {
      sumGrade += g;
      gradeCount++;
    }
  }
  const lapses = agains;

  // ---- Always-current population flags (isNew, isDue, isStale) ------------
  //
  // %New / %Stale / Due describe the card's CURRENT state in the KB — they
  // don't shift when the user narrows the period. A card with reviews from
  // years ago but none in "This Week" should not count as new.
  let everGradeable = false;
  for (const h of effective) {
    if (isGradeable(h.score)) { everGradeable = true; break; }
  }
  const isNew = !everGradeable;

  const nextRep = card.nextRepetitionTime as number | undefined;
  const isDue = (nextRep ?? Infinity) <= now;

  let isStale = false;
  const lastRep = effective.length > 0 ? effective[effective.length - 1] : null;
  if (lastRep && nextRep && nextRep > lastRep.date) {
    const lastInterval = nextRep - lastRep.date;
    const staleDate = lastRep.date + 2 * lastInterval;
    isStale = now > staleDate;
  }

  // ---- Cost ---------------------------------------------------------------
  // Period = 'all' → existing per-card coverage formula (lifetime cost).
  // Finite period → annualized: time spent in period / period length in years.
  let cost: number | null = null;
  if (totalTimeMs > 0) {
    const totalMinutes = totalTimeMs / 60000;
    const yearMs = 1000 * 60 * 60 * 24 * 365;
    if (isAllPeriod) {
      let firstGradeableDate: number | null = null;
      for (const h of effective) {
        if (isGradeable(h.score)) { firstGradeableDate = h.date; break; }
      }
      if (firstGradeableDate) {
        if (nextRep && nextRep > now) {
          const coverageYears = (nextRep - firstGradeableDate) / yearMs;
          if (coverageYears > 0) cost = totalMinutes / coverageYears;
        } else {
          const ageYears = (now - firstGradeableDate) / yearMs;
          if (ageYears > 0) cost = totalMinutes / ageYears;
        }
      }
    } else {
      const periodYears = (endMs - startMs) / yearMs;
      if (periodYears > 0) cost = totalMinutes / periodYears;
    }
  }

  // ---- FSRS state + Avg pR ------------------------------------------------
  // FSRS state (D / R today / S) is always-current — replayed over the full
  // effective history regardless of period.
  // Avg pR (predicted retrievability at the moment of each rep) is averaged
  // only over reps in the period — same period filter as Reps/Time/Retention.
  let sumPredR = 0;
  let predRCount = 0;
  let d: number | null = null;
  let s: number | null = null;
  let rToday: number | null = null;

  if (!isNew) {
    try {
      const steps = computeFSRSStatesPerReview(effective, weights);
      // FSRS leaves step.r null for learning/relearning state reps; we want
      // Avg pR's denominator to match Retention's (every gradeable rep except
      // the first of each FSRS "lifetime"), so we compute the forgetting-curve
      // r ourselves for those cases using the previous gradeable rep's stability.
      const { w } = resolveWeights(weights);
      const DECAY = -w[20];
      const FACTOR = Math.pow(0.9, 1 / DECAY) - 1;

      let lastGradeableIdx: number | null = null;
      for (let i = 0; i < effective.length; i++) {
        const h = effective[i];

        // RESET ends the current "lifetime" — the next gradeable rep is
        // effectively a brand-new card and gets skipped just like the first
        // rep of a fresh card.
        if (h.score === QueueInteractionScore.RESET) {
          lastGradeableIdx = null;
          continue;
        }
        if (!isGradeable(h.score)) continue;

        // First gradeable rep of this lifetime: no prior FSRS state to predict
        // from. Per design, we skip it (no contribution to numerator or
        // denominator), but still advance the reference for downstream reps.
        if (lastGradeableIdx === null) {
          lastGradeableIdx = i;
          continue;
        }

        if (inPeriod(h)) {
          const step = steps[i];
          let r: number | null = step?.r ?? null;
          if (r === null) {
            // Learning/relearning rep: replicate the FSRS forgetting curve
            // using the previous gradeable rep's stability.
            const prevS = steps[lastGradeableIdx]?.s ?? 0;
            const prevDate = effective[lastGradeableIdx].date;
            const elapsedDays = (h.date - prevDate) / (1000 * 60 * 60 * 24);
            if (prevS > 0 && elapsedDays >= 0) {
              r = forgettingCurve(elapsedDays, prevS, DECAY, FACTOR);
            }
          }
          if (r !== null && Number.isFinite(r)) {
            sumPredR += r;
            predRCount++;
          }
        }

        lastGradeableIdx = i;
      }

      const state = computeFSRSState(effective, weights);
      if (state) {
        d = state.d;
        s = state.s;
        rToday = state.r;
      }
    } catch {
      // FSRS failure on a single card is non-fatal — its FSRS-derived stats just stay null.
    }
  }

  return {
    isDue,
    isNew,
    isStale,
    isUnscheduled: nextRep === null || nextRep === undefined,
    isPaused,
    gradeableReps,
    totalTimeMs,
    agains,
    lapses,
    cost,
    sumPredR,
    predRCount,
    sumGrade,
    gradeCount,
    d,
    s,
    rToday,
  };
}

function accumulate(acc: AccData, stats: PerCardStats, priority: number) {
  acc.count++;
  if (priority < acc.minPriority) acc.minPriority = priority;
  if (priority > acc.maxPriority) acc.maxPriority = priority;
  // A card in a paused deck may also be unscheduled. Count it once, under
  // `paused`: the pause explains the whole subtree and is the thing to undo.
  if (stats.isPaused) acc.paused++;
  else if (stats.isUnscheduled) acc.unscheduled++;

  // Due-ness is reported for what RemNote would actually serve, so suppressed
  // cards are excluded even though they carry a real nextRepetitionTime.
  if (stats.isDue && !stats.isPaused) acc.due++;
  if (stats.isNew) {
    if (stats.isUnscheduled || stats.isPaused) acc.newUnscheduled++;
    else acc.newCount++;
  }
  if (stats.isStale && !stats.isPaused) acc.staleCount++;

  acc.totGradeableReps += stats.gradeableReps;
  acc.totTimeMs += stats.totalTimeMs;
  acc.totAgains += stats.agains;

  if (!stats.isNew) {
    acc.totLapses += stats.lapses;
    acc.nonNewCards++;
  }
  if (stats.cost !== null) {
    acc.sumCost += stats.cost;
    acc.cardsWithCost++;
  }

  acc.sumPredR += stats.sumPredR;
  acc.predRCount += stats.predRCount;
  acc.sumGrade += stats.sumGrade;
  acc.gradeCount += stats.gradeCount;

  // FSRS state describes what you are currently practising, so unscheduled
  // cards are left out — an unpractisable card's retrievability decays toward
  // zero and would drag the bucket's R down for no actionable reason.
  if (
    !stats.isUnscheduled &&
    !stats.isPaused &&
    stats.d !== null &&
    stats.s !== null &&
    stats.rToday !== null
  ) {
    acc.sumD += stats.d;
    acc.sumS += stats.s;
    acc.sumRtoday += stats.rToday;
    acc.fsrsCount++;
  }
}

function finalize(acc: AccData, label: string): CardBucketStats {
  const cards = acc.count;
  const priorityRange =
    cards > 0 && Number.isFinite(acc.minPriority) && Number.isFinite(acc.maxPriority)
      ? `${acc.minPriority}-${acc.maxPriority}`
      : '—';
  // Every practice-shaped percentage is measured against the cards that can
  // actually be practised. Counting unscheduled cards as "done" was reporting
  // 100% for buckets holding hundreds of cards no queue will ever show.
  const active = cards - acc.unscheduled - acc.paused;
  const donePct = active > 0 ? ((active - acc.due) / active) * 100 : 100;
  const newPct = active > 0 ? (acc.newCount / active) * 100 : 0;
  const stalePct = active > 0 ? (acc.staleCount / active) * 100 : 0;
  const avgReps = cards > 0 ? acc.totGradeableReps / cards : 0;
  const avgTimeMs = cards > 0 ? acc.totTimeMs / cards : 0;
  const cpm = acc.totTimeMs > 0 ? acc.totGradeableReps / (acc.totTimeMs / 60000) : 0;
  const avgTimePerRepMs = acc.totGradeableReps > 0 ? acc.totTimeMs / acc.totGradeableReps : 0;
  const avgCost = acc.cardsWithCost > 0 ? acc.sumCost / acc.cardsWithCost : 0;
  const avgLapses = acc.nonNewCards > 0 ? acc.totLapses / acc.nonNewCards : 0;
  const retention =
    acc.totGradeableReps > 0
      ? ((acc.totGradeableReps - acc.totAgains) / acc.totGradeableReps) * 100
      : 0;
  const avgPredR = acc.predRCount > 0 ? (acc.sumPredR / acc.predRCount) * 100 : 0;
  // R-deviation only meaningful when both retention and predicted R have a basis.
  const rDevPP = acc.totGradeableReps > 0 && acc.predRCount > 0 ? retention - avgPredR : 0;
  const avgGrade = acc.gradeCount > 0 ? acc.sumGrade / acc.gradeCount : 0;
  const avgD = acc.fsrsCount > 0 ? acc.sumD / acc.fsrsCount : 0;
  const avgS = acc.fsrsCount > 0 ? acc.sumS / acc.fsrsCount : 0;
  const avgRtoday = acc.fsrsCount > 0 ? (acc.sumRtoday / acc.fsrsCount) * 100 : 0;

  return {
    label,
    priorityRange,
    cards,
    unscheduled: acc.unscheduled,
    paused: acc.paused,
    active,
    due: acc.due,
    donePct,
    newCount: acc.newCount,
    newPct,
    newUnscheduled: acc.newUnscheduled,
    staleCount: acc.staleCount,
    stalePct,
    totReps: acc.totGradeableReps,
    totTimeMs: acc.totTimeMs,
    avgReps,
    avgTimeMs,
    cpm,
    avgTimePerRepMs,
    avgCostMinPerYear: avgCost,
    avgLapses,
    retention,
    avgPredR,
    rDevPP,
    avgGrade,
    avgD,
    avgRtoday,
    avgS,
  };
}

/**
 * Replay FSRS over every card and aggregate per priority-percentile bucket.
 *
 * The expensive part is `plugin.card.getAll()` (one call) and the per-card
 * FSRS replay (CPU only — no further async). We yield to the event loop every
 * `YIELD_EVERY` cards so the popup stays responsive while progress updates.
 */
export interface PeriodSpec {
  /** Period id (e.g. 'thisYear'). Stored on the breakdown for cache-sync. */
  id: string;
  startMs: number;
  endMs: number;
  customStart: string;
  customEnd: string;
}

/**
 * One exported row per card — the raw material behind every aggregate above.
 * Emitted through the optional `onRow` callback so an export can reuse the
 * exact same population, priority inheritance, bucketing and New/Due/Stale
 * predicates the table renders (no second, drifting implementation).
 */
export interface CardAnalyticsRow {
  cardId: string;
  remId: string;
  cardType: string;
  /** For cloze cards, the cloze id the card is bound to; null otherwise. It is
   *  what lets us ask whether the Rem's text still contains this card's markup. */
  clozeId: string | null;
  /** Inherited priority of the owning Rem (1-100). */
  priority: number;
  /** 1-based rank percentile within the sorted card population (0-100). */
  percentile: number;
  /** Bucket label the card was counted in, e.g. "0-10%". */
  bucket: string;
  isNew: boolean;
  isDue: boolean;
  isStale: boolean;
  /**
   * Why the card is / isn't due, from `nextRepetitionTime` alone:
   * - `unscheduled` — null/undefined next time. RemNote leaves this empty for
   *   cards it will never surface: disabled practice direction, and some
   *   never-scheduled states. These can never be Due, so no queue and no
   *   Priority Review Document will ever pick them up.
   * - `due` — next time ≤ now.
   * - `scheduled` — next time in the future.
   */
  scheduleState: 'unscheduled' | 'due' | 'scheduled';
  /**
   * Inside a paused deck. Schedulable — pausing does not clear
   * `nextRepetitionTime` — but the queue will not serve it. Always false when no
   * paused-deck scan was supplied.
   */
  inPausedDeck: boolean;
  /** Raw next repetition time (ms epoch) or null. */
  nextRepetitionTime: number | null;
  createdAt: number | null;
  /** Total history entries (every interaction, gradeable or not). */
  historyEntries: number;
  /** Gradeable reps over the FULL lifetime (ignores period AND ignorePreReset). */
  gradeableRepsLifetime: number;
  /** Gradeable reps in the effective slice — what `isNew` actually looks at. */
  gradeableRepsEffective: number;
  /** True when the history contains at least one RESET entry. */
  hasReset: boolean;
  /** Non-gradeable interactions (SKIP / TOO_SOON / RESET / VIEWED…) lifetime. */
  nonGradeableInteractions: number;
  /** Score of the last history entry, or null when there is no history. */
  lastScore: number | null;
  lastInteractionDate: number | null;
}

/**
 * Lifetime + effective history facts for one card. Kept next to
 * `computeCardStats` so the RESET slicing rule stays defined in one place.
 */
function describeCardHistory(card: any, ignorePreReset: boolean) {
  const history: any[] = card.repetitionHistory ?? [];
  const sorted = [...history].sort((a: any, b: any) => a.date - b.date);
  let effective = sorted;
  if (ignorePreReset) {
    const lastResetIdx = sorted.map((h: any) => h.score).lastIndexOf(QueueInteractionScore.RESET);
    if (lastResetIdx !== -1) effective = sorted.slice(lastResetIdx + 1);
  }
  let gradeableRepsLifetime = 0;
  let hasReset = false;
  for (const h of sorted) {
    if (isGradeable(h.score)) gradeableRepsLifetime++;
    if (h.score === QueueInteractionScore.RESET) hasReset = true;
  }
  let gradeableRepsEffective = 0;
  for (const h of effective) if (isGradeable(h.score)) gradeableRepsEffective++;
  const last = sorted.length > 0 ? sorted[sorted.length - 1] : null;
  return {
    historyEntries: sorted.length,
    gradeableRepsLifetime,
    gradeableRepsEffective,
    hasReset,
    nonGradeableInteractions: sorted.length - gradeableRepsLifetime,
    lastScore: last ? (last.score as number) : null,
    lastInteractionDate: last ? (last.date as number) : null,
  };
}

function cardTypeLabel(type: any): string {
  if (typeof type === 'string') return type;
  if (type && typeof type === 'object' && 'clozeId' in type) return 'cloze';
  return 'unknown';
}

export async function computeCardAnalyticsBreakdown(
  plugin: RNPlugin,
  cardPriorityInfos: CardPriorityInfo[],
  weights: number[] | null,
  cardCapMs: number,
  ignorePreReset: boolean,
  period: PeriodSpec,
  onProgress?: (done: number, total: number) => void,
  /** Optional per-card sink — lets an export capture the raw rows behind the aggregates. */
  onRow?: (row: CardAnalyticsRow) => void,
  /**
   * Rem ids suppressed by a paused deck, from lib/paused_decks.ts. Pass null
   * when no scan has run — the paused column then reports 0 and the caller is
   * expected to say so, rather than let "we never looked" read as "none".
   */
  pausedRemIds?: Set<string> | null,
): Promise<CardAnalyticsBreakdown> {
  const { startMs, endMs } = period;
  // Map remId → inherited rem priority. Filter out rems with explicit zero cards.
  const remPriority = new Map<string, number>();
  for (const info of cardPriorityInfos) {
    if (info.cardCount === undefined || info.cardCount > 0) {
      remPriority.set(info.remId, info.priority);
    }
  }

  // Pull every card from the KB (includes disabled/paused — matches batch.ts pattern).
  const allCards = (await plugin.card.getAll()) || [];

  const validCards: any[] = [];
  let cardsSkippedNoPriority = 0;
  for (const c of allCards) {
    if (remPriority.has(c.remId)) validCards.push(c);
    else cardsSkippedNoPriority++;
  }

  // Sort by inherited priority so we can bucket by 1-based index percentile.
  validCards.sort((a, b) => (remPriority.get(a.remId)! - remPriority.get(b.remId)!));

  const N = validCards.length;
  /**
   * Population that DEFINES the deciles. Unscheduled cards are excluded: a
   * disabled card, a table row or a cloze whose markup is gone is not something
   * the user intends to practise, and leaving them in lets them push real cards
   * across percentile boundaries.
   *
   * Cards in a PAUSED deck stay in. Pausing defers a card, it does not demote
   * it — excluding them would shift every other card's percentile when a deck is
   * paused and shift it back when unpaused, so priority would drift as a side
   * effect of a scheduling decision. They keep a real nextRepetitionTime, which
   * is exactly what distinguishes them here.
   *
   * Unscheduled cards are still REPORTED in every bucket (the Unsched column);
   * they are placed by where their priority falls among the ranked cards, so a
   * bucket still accounts for all of its cards. Only bucket SIZE is defined by
   * the ranked population.
   */
  const isUnscheduledCard = (c: any) =>
    c.nextRepetitionTime === null || c.nextRepetitionTime === undefined;
  const rankedTotal = validCards.reduce((n, c) => (isUnscheduledCard(c) ? n : n + 1), 0);
  const rankDenominator = rankedTotal > 0 ? rankedTotal : N;
  let rankedSeen = 0;
  const bucketAccs: AccData[] = Array.from({ length: 10 }, makeAcc);
  const overallAcc = makeAcc();
  // Per-absolute-priority accumulators (priority 0..100, inclusive). Used to
  // produce a prefix-sum table so the threshold slider in the view becomes a
  // pure array lookup instead of re-aggregating on every drag.
  const byPriorityAccs: AccData[] = Array.from({ length: 101 }, makeAcc);
  const now = Date.now();

  const YIELD_EVERY = 1500;

  if (onProgress) onProgress(0, N);

  for (let i = 0; i < N; i++) {
    const card = validCards[i];
    const priority = remPriority.get(card.remId)!;
    // 1-based index percentile over the RANKED population. An unscheduled card
    // takes the percentile of the ranked cards it sits between (the array is
    // sorted by priority, so `rankedSeen` is its lower-bound rank) — it is
    // placed by its priority without being allowed to shift anyone else's.
    const cardIsUnscheduled = isUnscheduledCard(card);
    if (!cardIsUnscheduled) rankedSeen++;
    const percentile = Math.min((Math.max(rankedSeen, 1) / rankDenominator) * 100, 100);
    const bIdx = Math.min(Math.floor(percentile / 10), 9);
    // Clamp priority into [0, 100] for the by-priority bucket index.
    const pIdx = Math.max(0, Math.min(100, Math.round(priority)));

    const isPaused = pausedRemIds ? pausedRemIds.has(card.remId) : false;
    const stats = computeCardStats(
      card, weights, now, cardCapMs, ignorePreReset, startMs, endMs, isPaused,
    );
    accumulate(bucketAccs[bIdx], stats, priority);
    accumulate(overallAcc, stats, priority);
    accumulate(byPriorityAccs[pIdx], stats, priority);

    if (onRow) {
      const nextRep = (card.nextRepetitionTime ?? null) as number | null;
      onRow({
        cardId: card._id,
        remId: card.remId,
        cardType: cardTypeLabel(card.type),
        clozeId:
          card.type && typeof card.type === 'object' && 'clozeId' in card.type
            ? String((card.type as any).clozeId)
            : null,
        priority,
        percentile,
        bucket: `${bIdx * 10}-${(bIdx + 1) * 10}%`,
        isNew: stats.isNew,
        isDue: stats.isDue,
        isStale: stats.isStale,
        scheduleState: nextRep === null ? 'unscheduled' : nextRep <= now ? 'due' : 'scheduled',
        inPausedDeck: isPaused,
        nextRepetitionTime: nextRep,
        createdAt: (card.createdAt ?? null) as number | null,
        ...describeCardHistory(card, ignorePreReset),
      });
    }

    if ((i + 1) % YIELD_EVERY === 0) {
      if (onProgress) onProgress(i + 1, N);
      // Yield to the event loop so the progress bar can repaint.
      await new Promise<void>((resolve) => setTimeout(resolve, 0));
    }
  }

  if (onProgress) onProgress(N, N);

  // Build prefix-sum accumulators: prefixAccs[T] aggregates every card with
  // priority ≤ T. Each entry is then finalized for direct rendering. Sliding
  // becomes an O(1) lookup at the view layer.
  const prefixAccs: AccData[] = new Array(101);
  let running = makeAcc();
  for (let t = 0; t <= 100; t++) {
    running = mergeAcc(running, byPriorityAccs[t]);
    // Clone so the array entries don't share the same underlying object
    // (otherwise every entry would point to the final accumulator).
    prefixAccs[t] = { ...running };
  }
  const byPriorityPrefix: CardBucketStats[] = prefixAccs.map((acc, t) =>
    finalize(acc, `Priority ≤ ${t}`),
  );

  return {
    buckets: bucketAccs.map((acc, i) => finalize(acc, `${i * 10}-${(i + 1) * 10}%`)),
    overall: finalize(overallAcc, 'All KB'),
    totalCards: N,
    computedAt: Date.now(),
    pausedScanApplied: !!pausedRemIds,
    cardsSkippedNoPriority,
    ignorePreReset,
    period: period.id,
    periodStartMs: period.startMs,
    periodEndMs: period.endMs,
    periodCustomStart: period.customStart,
    periodCustomEnd: period.customEnd,
    byPriorityPrefix,
  };
}
